### ISSUE TITLE
Suggestion:  Open a resource avaliable for download as packed DLL or download from nuget.

### ISSUE THREAD

**Issue by BeanTang** [jilleJr/Newtonsoft.Json-for-Unity#10]
Because sometime we used to reference a project dll which referenced json.dll for unity.

Such as I have a Project about Integrated the Netwrok communications.  And the project reference the json.dll.  
Then Build the project to dll which was used by Unity.

**Comment by jilleJr** [comment]
Good note. Related to #7. Will consider releasing on NuGet so you can reference it in your class libraries.

For now a possible workaround is as I mentioned in #7:

> _In a different project of mine I did a workaround where I referenced the  `/Src/Newtonsoft.Json/Newtonsoft.Json.csproj` project from this repo instead of the one from NuGet. That way when it compiled it did so without the strong name reference._

**Comment by jilleJr** [comment]
From release 12.0.102 the package will be signed and a NuGet publish will no longer be needed. If you need to use Newtonsoft.Json outside of Unity, such as in a class library developed in Visual Studio, then use the official Newtonsoft.Json. Newtonsoft.Json-for-Unity is only a replacement for Newtonsoft.Json within Unity.

This issue will be closed due to the suggestions motivation having been dismissed.
