### ISSUE TITLE
Suggestion: Add git deployment for UPM

### ISSUE THREAD

**Issue by jilleJr** [jilleJr/Newtonsoft.Json-for-Unity#33]
## Description

Providing the package via a git branch is neat for then you just need to add the git url, and not needing to add a custom registry provider.

Downside is that the update functionality disappears, and users are required to have a version of git installed. Could maybe be fixed if try to comply with the https://github.com/mob-sakai/UpmGitExtension that provides update functionality.

## Motivation

Package can then be added to https://openupm.com/

## Suggested solution

Provide an `upm` branch containing the built package, basically the contents of the `Src/Newtonsoft.Json-for-Unity/` folder but also with the built binaries.

To be able to specify a version there should also be tags for each version. Such as `12.0.102-upm` and `12.0.201-upm` in addition to the existing tags. Or perhaps switch and use the tags `12.0.102` solely for this purpose as the [mob-sakai/UpmGitExtension](https://github.com/mob-sakai/UpmGitExtension) would only provide tags to switch between.

Another solution would be to have a separate repository just for the UPM via git releases.

## Inspiration sources

Used this routine previously in ZIFRO Playground

<https://github.com/zifro-playground/ui/tree/upm#readme>

**Comment by favoyang** [comment]
Hi @jilleJr,

I'm the creator of OpenUPM. Thanks for the very detailed proposal. I write a blog for how to create an up-to-date UPM branch https://medium.com/openupm/how-to-maintain-upm-package-part-1-7b4daf88d4c4, it may be slightly related. Overall I agree with the idea to maintain an upm branch and create tags from it.

**Comment by jilleJr** [comment]
Great to see you @favoyang! Nice blog post, didn't know about the samples thing. Very nice.

I'll continue work on also delivering the package via git, but how far away could OpenUPM be from supporting packages with scoped registries?

**Comment by favoyang** [comment]
> how far away could OpenUPM be from supporting packages with scoped registries?
Do you mean that the OpenUPM platform could support packages published in other 3rd party registry, like a proxy mode or synchronization mode? If not, please let me know your intention.

**Comment by jilleJr** [comment]
Ok yea so my package is deployed on Cloudsmith to be pulled using the NPM protocol that UPM uses, instead of relying on a local installation of git.

So as a configuration on the OpenUPM package it would be cool to be able to supply a scoped registry config like so:
```json
{
  "scopedRegistries": [
    {
      "name": "Packages from jillejr",
      "url": "https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity/",
      "scopes": ["jillejr"]
    }
  ],
  "dependencies": {
    /.../
  }
}
```
and then the package could be added by adding
`"jillejr.newtonsoft.json-for-unity": "12.0.201",`
instead of
`"jillejr.newtonsoft.json-for-unity": "https://github.com/jilleJr/Newtonsoft.Json-for-Unity.git#upm",`

Also the not-requiring-git-installed thing is very beneficial IMO.

**Comment by jilleJr** [comment]
My bad! Correction: I assumed all packages from OpenUPM was downloaded via git. So the correct flow is that OpenUPM downloads the git version and deploys to it's own NPM registry, yes?

**Comment by favoyang** [comment]
I see. So cloudsmith is a packager hosting provider, with a high monthly price, but friendly for opensource project. Your package is deployed to cloudsmith probably with manually build-then-release process?

OpenUPM is just another npm protocol registry (UPM), but it's managed. Our build pipelines monitor and fetch git tags that are valid semver (vx.y.z or x.y.z, ...), then bundle the packages. Having an UPM branch is a popular mid-step, because it can be achieved by the CI (`git subtree split/push ...), and make it easier to create a git tag. Though build pipelines can detect the package.json at any folder, so tagging from the upm branch is not necessary.

However, in your case the path is half baked, with only some meta data for UPM. Then you have to create the a working upm branch with both meta data and the binary/scr. Then create git tag from the upm branch.

**Comment by favoyang** [comment]
> So the correct flow is that OpenUPM downloads the git version and deploys to it's own NPM registry, yes?

Yes.

**Comment by favoyang** [comment]
The openupm-cli can be used to install any 3rd party registry.

```
openupm --registry https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity/ search newtonsoft
┌──────────────────────────────────────────────┬──────────────────────┬──────────────┬────────────┐
│ Name                                         │ Version              │ Author       │ Date       │
├──────────────────────────────────────────────┼──────────────────────┼──────────────┼────────────┤
│ jillejr.newtonsoft.json-for-unity            │ 12.0.201             │              │ 2020-01-03 │
├──────────────────────────────────────────────┼──────────────────────┼──────────────┼────────────┤
│ jillejr.newtonsoft.json-for-unity            │ 12.0.102             │              │ 2019-12-30 │
├──────────────────────────────────────────────┼──────────────────────┼──────────────┼────────────┤
│ jillejr.newtonsoft.json-for-unity            │ 12.0.101             │              │ 2019-11-26 │
└──────────────────────────────────────────────┴──────────────────────┴──────────────┴────────────┘

openupm --registry https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity/ add newtonsoft
added: jillejr.newtonsoft.json-for-unity@12.0.201
manifest updated, please open unity project to apply changes

cat Packages/manifest.json
  "scopedRegistries": [
    {
      "name": "npm.cloudsmith.io",
      "url": "https://npm.cloudsmith.io/jillejr/newtonsoft-json-for-unity",
      "scopes": [
        "io.cloudsmith",
        "jillejr.newtonsoft.json-for-unity"
      ]
    }
]  
```

**Comment by jilleJr** [comment]
> The openupm-cli can be used to install any 3rd party registry.

That's a really neat functionality!

So plans are to fix UPM branch so that it can (indirectly) be hosted via OpenUPM's registry.

One thing I really like with Cloudsmith's NPM registry (don't know what they use for the backend) is that it supports the "list all packages" endpoint that the UPM GUI uses, so by just adding my registry I can see my package without having it installed. Such a feature is very nice when I soon will make the Newtonsoft.Json-for-Unity.Converters package available because the package will already show in the list without the user needing to tamper with the manifest.json file again.

Perhaps you could look into adding that endpoint to the OpenUPM registry, or perhaps that would clog up the Packages tab in the GUI?

**Comment by favoyang** [comment]
I guess the `list all packages` feature would be simialr to one of below

**website**

https://openupm.com/packages/ # the web page list all packages.
https://openupm.com/contributors/<username\> # the web page list all packages of a github (not implemented yet, in backlog).

**CLI**

`openupm all` # list all package names on the registry (not implemented yet, TBD).
`openupm search jillejr` # search keyword (namespace) for related packages.

**package manager ui**

The reason that your registry can list all packages in the package manager ui, that because
1. your registry supports the old `/-/all` endpoint (OpenUPM registry does too).
2. you specify a wider scope
```
      "scopes": ["jillejr"]
vs 
      "scopes": [
        "io.cloudsmith",
        "jillejr.newtonsoft.json-for-unity"
      ]
```
  while openupm-cli can not do that, because it cannot ensure that the root namespace is exclusive for openupm registry (com.example.pkg => com.example => com).

I have to write a custom plugin to show all openupm packages into the package manager ui https://github.com/openupm/openupm/issues/10

**Comment by jilleJr** [comment]
Woop woop https://github.com/openupm/openupm/pull/335 🎉

Also updated wiki to show how to add the package via the OpenUPM registry https://github.com/jilleJr/Newtonsoft.Json-for-Unity/wiki/Installation-via-OpenUPM#installing-the-package-openupm-registry

**Comment by favoyang** [comment]
Awesome!
